export const ACHIEVEMENT_REPOSITORY = Symbol('ACHIEVEMENT_REPOSITORY');
export const ACHIEVEMENT_METRICS_REPOSITORY = Symbol('ACHIEVEMENT_METRICS_REPOSITORY');
export const ACHIEVEMENT_USER_REPOSITORY = Symbol('ACHIEVEMENT_USER_REPOSITORY');
export const ACHIEVEMENT_NOTIFICATION_REPOSITORY = Symbol('ACHIEVEMENT_NOTIFICATION_REPOSITORY');
export const ACHIEVEMENT_ACTIVITY_REPOSITORY = Symbol('ACHIEVEMENT_ACTIVITY_REPOSITORY');
