export const PROFILE_PIN_REPOSITORY = Symbol('PROFILE_PIN_REPOSITORY');
export const PROFILE_PIN_USER_REPOSITORY = Symbol('PROFILE_PIN_USER_REPOSITORY');
export const PROFILE_PIN_GAME_REPOSITORY = Symbol('PROFILE_PIN_GAME_REPOSITORY');
export const PROFILE_PIN_REVIEW_REPOSITORY = Symbol('PROFILE_PIN_REVIEW_REPOSITORY');
export const PROFILE_PIN_COLLECTION_REPOSITORY = Symbol('PROFILE_PIN_COLLECTION_REPOSITORY');
export const PROFILE_PIN_ACHIEVEMENT_REPOSITORY = Symbol('PROFILE_PIN_ACHIEVEMENT_REPOSITORY');
