export const QUOTE_REPOSITORY = Symbol('QUOTE_REPOSITORY');
export const QUOTE_USER_REPOSITORY = Symbol('QUOTE_USER_REPOSITORY');
export const QUOTE_NOTIFICATION_REPOSITORY = Symbol('QUOTE_NOTIFICATION_REPOSITORY');
