export const EVENT_REPOSITORY = Symbol('EVENT_REPOSITORY');
export const EVENT_PARTICIPATION_REPOSITORY = Symbol('EVENT_PARTICIPATION_REPOSITORY');
export const EVENT_USER_REPOSITORY = Symbol('EVENT_USER_REPOSITORY');
export const EVENT_INVITE_REPOSITORY = Symbol('EVENT_INVITE_REPOSITORY');
export const EVENT_NOTIFICATION_REPOSITORY = Symbol('EVENT_NOTIFICATION_REPOSITORY');
export const EVENT_GAME_REPOSITORY = Symbol('EVENT_GAME_REPOSITORY');
export const EVENT_COMMUNITY_MEMBER_REPOSITORY = Symbol('EVENT_COMMUNITY_MEMBER_REPOSITORY');
export const EVENT_COMMUNITY_REPOSITORY = Symbol('EVENT_COMMUNITY_REPOSITORY');
