export const REACTION_REPOSITORY = Symbol('REACTION_REPOSITORY');
export const REACTION_USER_REPOSITORY = Symbol('REACTION_USER_REPOSITORY');
export const REACTION_POST_REPOSITORY = Symbol('REACTION_POST_REPOSITORY');
export const REACTION_REVIEW_REPOSITORY = Symbol('REACTION_REVIEW_REPOSITORY');
export const REACTION_COMMENT_REPOSITORY = Symbol('REACTION_COMMENT_REPOSITORY');
export const REACTION_COLLECTION_REPOSITORY = Symbol('REACTION_COLLECTION_REPOSITORY');
export const REACTION_TIER_LIST_REPOSITORY = Symbol('REACTION_TIER_LIST_REPOSITORY');
export const REACTION_NOTIFICATION_REPOSITORY = Symbol('REACTION_NOTIFICATION_REPOSITORY');
