export const CONVERSATION_REPOSITORY = Symbol('CONVERSATION_REPOSITORY');
export const CONVERSATION_PARTICIPANT_REPOSITORY = Symbol('CONVERSATION_PARTICIPANT_REPOSITORY');
export const MESSAGE_REPOSITORY = Symbol('MESSAGE_REPOSITORY');
export const MESSAGING_USER_REPOSITORY = Symbol('MESSAGING_USER_REPOSITORY');
