export const COLLECTION_REPOSITORY = Symbol('COLLECTION_REPOSITORY');
export const COLLECTION_ENTRY_REPOSITORY = Symbol('COLLECTION_ENTRY_REPOSITORY');
export const COLLECTION_USER_REPOSITORY = Symbol('COLLECTION_USER_REPOSITORY');
export const COLLECTION_GAME_REPOSITORY = Symbol('COLLECTION_GAME_REPOSITORY');
