export const FRIENDSHIP_REPOSITORY = Symbol('FRIENDSHIP_REPOSITORY');
export const PRESENCE_REPOSITORY = Symbol('PRESENCE_REPOSITORY');
export const FRIENDS_USER_REPOSITORY = Symbol('FRIENDS_USER_REPOSITORY');
export const FRIENDS_BLOCK_REPOSITORY = Symbol('FRIENDS_BLOCK_REPOSITORY');
export const FRIENDS_FOLLOW_REPOSITORY = Symbol('FRIENDS_FOLLOW_REPOSITORY');
export const FRIENDS_NOTIFICATION_REPOSITORY = Symbol('FRIENDS_NOTIFICATION_REPOSITORY');
export const FRIENDS_ACTIVITY_REPOSITORY = Symbol('FRIENDS_ACTIVITY_REPOSITORY');
