export const GAME_REPOSITORY = Symbol('GAME_REPOSITORY');
export const GAME_LIBRARY_ENTRY_REPOSITORY = Symbol('GAME_LIBRARY_ENTRY_REPOSITORY');
/** D3.25 — docs/18_CATALOG/GAME_METADATA_ARCHITECTURE.md */
export const GAME_METADATA_REPOSITORY = Symbol('GAME_METADATA_REPOSITORY');
