export const ACTIVITY_REPOSITORY = Symbol('ACTIVITY_REPOSITORY');
export const ACTIVITY_POST_REPOSITORY = Symbol('ACTIVITY_POST_REPOSITORY');
export const ACTIVITY_REVIEW_REPOSITORY = Symbol('ACTIVITY_REVIEW_REPOSITORY');
export const ACTIVITY_COLLECTION_REPOSITORY = Symbol('ACTIVITY_COLLECTION_REPOSITORY');
export const ACTIVITY_TIER_LIST_REPOSITORY = Symbol('ACTIVITY_TIER_LIST_REPOSITORY');
export const ACTIVITY_COMMENT_REPOSITORY = Symbol('ACTIVITY_COMMENT_REPOSITORY');
export const ACTIVITY_USER_REPOSITORY = Symbol('ACTIVITY_USER_REPOSITORY');
/** Optional — used by review-feed popularity / hidden-gems slices. */
export const ACTIVITY_GAME_REPOSITORY = Symbol('ACTIVITY_GAME_REPOSITORY');
