export const CREATOR_USER_REPOSITORY = Symbol('CREATOR_USER_REPOSITORY');
export const CREATOR_GAME_REPOSITORY = Symbol('CREATOR_GAME_REPOSITORY');
export const CREATOR_FOLLOW_REPOSITORY = Symbol('CREATOR_FOLLOW_REPOSITORY');
