/**
 * DI tokens for Profile Hero composition (D3.24 / PROFILE_V2.md).
 */
export const PROFILE_HERO_USER_REPOSITORY = Symbol('PROFILE_HERO_USER_REPOSITORY');
export const PROFILE_HERO_METRICS_REPOSITORY = Symbol('PROFILE_HERO_METRICS_REPOSITORY');
export const PROFILE_HERO_LIBRARY_REPOSITORY = Symbol('PROFILE_HERO_LIBRARY_REPOSITORY');
export const PROFILE_HERO_PIN_REPOSITORY = Symbol('PROFILE_HERO_PIN_REPOSITORY');
export const PROFILE_HERO_ARCHETYPE_REPOSITORY = Symbol('PROFILE_HERO_ARCHETYPE_REPOSITORY');
export const PROFILE_HERO_REPUTATION_REPOSITORY = Symbol('PROFILE_HERO_REPUTATION_REPOSITORY');
