export const POST_REPOSITORY = Symbol('POST_REPOSITORY');
export const POST_USER_REPOSITORY = Symbol('POST_USER_REPOSITORY');
export const POST_GAME_REPOSITORY = Symbol('POST_GAME_REPOSITORY');
export const POST_COMMUNITY_REPOSITORY = Symbol('POST_COMMUNITY_REPOSITORY');
export const POST_COMMUNITY_MEMBER_REPOSITORY = Symbol('POST_COMMUNITY_MEMBER_REPOSITORY');
export const POST_ACTIVITY_REPOSITORY = Symbol('POST_ACTIVITY_REPOSITORY');
export const POST_COMMUNITY_ACTIVITY_REPOSITORY = Symbol('POST_COMMUNITY_ACTIVITY_REPOSITORY');
/** D3.24 */
export const POST_REPOST_REPOSITORY = Symbol('POST_REPOST_REPOSITORY');
export const POST_POLL_REPOSITORY = Symbol('POST_POLL_REPOSITORY');
export const POST_POLL_VOTE_REPOSITORY = Symbol('POST_POLL_VOTE_REPOSITORY');
export const POST_BOOKMARK_REPOSITORY = Symbol('POST_BOOKMARK_REPOSITORY');
export const POST_NOTIFICATION_REPOSITORY = Symbol('POST_NOTIFICATION_REPOSITORY');
