export const DISCOVER_REPOSITORY = Symbol('DISCOVER_REPOSITORY');
export const DISCOVER_COMMUNITY_MEMBER_REPOSITORY = Symbol('DISCOVER_COMMUNITY_MEMBER_REPOSITORY');
export const DISCOVER_COMMUNITY_REPOSITORY = Symbol('DISCOVER_COMMUNITY_REPOSITORY');
export const DISCOVER_EVENT_PARTICIPATION_REPOSITORY = Symbol(
  'DISCOVER_EVENT_PARTICIPATION_REPOSITORY',
);
