export const ARCHETYPE_REPOSITORY = Symbol('ARCHETYPE_REPOSITORY');
export const ARCHETYPE_METRICS_REPOSITORY = Symbol('ARCHETYPE_METRICS_REPOSITORY');
export const ARCHETYPE_USER_REPOSITORY = Symbol('ARCHETYPE_USER_REPOSITORY');
