export const TIER_LIST_REPOSITORY = Symbol('TIER_LIST_REPOSITORY');
export const TIER_SLOT_REPOSITORY = Symbol('TIER_SLOT_REPOSITORY');
export const TIER_LIST_USER_REPOSITORY = Symbol('TIER_LIST_USER_REPOSITORY');
export const TIER_LIST_GAME_REPOSITORY = Symbol('TIER_LIST_GAME_REPOSITORY');
