/** Worker-scoped repository tokens (processors only). */
export const WORKER_UPLOAD_REPOSITORY = Symbol('GMRLOG_WORKER_UPLOAD_REPOSITORY');
export const WORKER_ACTIVITY_REPOSITORY = Symbol('GMRLOG_WORKER_ACTIVITY_REPOSITORY');
export const WORKER_COMMUNITY_ACTIVITY_REPOSITORY = Symbol(
  'GMRLOG_WORKER_COMMUNITY_ACTIVITY_REPOSITORY',
);
export const WORKER_NOTIFICATION_REPOSITORY = Symbol('GMRLOG_WORKER_NOTIFICATION_REPOSITORY');
export const WORKER_EVENT_REPOSITORY = Symbol('GMRLOG_WORKER_EVENT_REPOSITORY');
export const WORKER_EVENT_PARTICIPATION_REPOSITORY = Symbol(
  'GMRLOG_WORKER_EVENT_PARTICIPATION_REPOSITORY',
);
