export const COMMUNITY_REPOSITORY = Symbol('COMMUNITY_REPOSITORY');
export const COMMUNITY_MEMBER_REPOSITORY = Symbol('COMMUNITY_MEMBER_REPOSITORY');
export const COMMUNITY_USER_REPOSITORY = Symbol('COMMUNITY_USER_REPOSITORY');
export const COMMUNITY_ACTIVITY_REPOSITORY = Symbol('COMMUNITY_ACTIVITY_REPOSITORY');
export const COMMUNITY_WIKI_REPOSITORY = Symbol('COMMUNITY_WIKI_REPOSITORY');
export const COMMUNITY_PIN_REPOSITORY = Symbol('COMMUNITY_PIN_REPOSITORY');
export const COMMUNITY_BADGE_REPOSITORY = Symbol('COMMUNITY_BADGE_REPOSITORY');
export const COMMUNITY_POST_REPOSITORY = Symbol('COMMUNITY_POST_REPOSITORY');
export const COMMUNITY_NOTIFICATION_REPOSITORY = Symbol('COMMUNITY_NOTIFICATION_REPOSITORY');
/** 3b.1b — §13's "N friends here" on a suggested circle. */
export const COMMUNITY_FRIENDSHIP_REPOSITORY = Symbol('COMMUNITY_FRIENDSHIP_REPOSITORY');
/** 7.1 — leaderboard "replies" points (comments on a community's posts). */
export const COMMUNITY_COMMENT_REPOSITORY = Symbol('COMMUNITY_COMMENT_REPOSITORY');
/** 7.1 — leaderboard "events hosted" points. */
export const COMMUNITY_EVENT_REPOSITORY = Symbol('COMMUNITY_EVENT_REPOSITORY');
export const COMMUNITY_EVENT_PARTICIPATION_REPOSITORY = Symbol(
  'COMMUNITY_EVENT_PARTICIPATION_REPOSITORY',
);
