/** D3.24 Game Hub — DI tokens (F6.3). Own repository bindings; no cross-service coupling. */
export const GAME_HUB_GAME_REPOSITORY = Symbol('GAME_HUB_GAME_REPOSITORY');
export const GAME_HUB_POST_REPOSITORY = Symbol('GAME_HUB_POST_REPOSITORY');
export const GAME_HUB_REVIEW_REPOSITORY = Symbol('GAME_HUB_REVIEW_REPOSITORY');
export const GAME_HUB_COLLECTION_REPOSITORY = Symbol('GAME_HUB_COLLECTION_REPOSITORY');
export const GAME_HUB_TIER_LIST_REPOSITORY = Symbol('GAME_HUB_TIER_LIST_REPOSITORY');
export const GAME_HUB_EVENT_REPOSITORY = Symbol('GAME_HUB_EVENT_REPOSITORY');
export const GAME_HUB_EVENT_PARTICIPATION_REPOSITORY = Symbol(
  'GAME_HUB_EVENT_PARTICIPATION_REPOSITORY',
);
export const GAME_HUB_COMMUNITY_REPOSITORY = Symbol('GAME_HUB_COMMUNITY_REPOSITORY');
export const GAME_HUB_COMMUNITY_MEMBER_REPOSITORY = Symbol('GAME_HUB_COMMUNITY_MEMBER_REPOSITORY');
export const GAME_HUB_LIBRARY_REPOSITORY = Symbol('GAME_HUB_LIBRARY_REPOSITORY');
export const GAME_HUB_USER_REPOSITORY = Symbol('GAME_HUB_USER_REPOSITORY');
